name       : gssdp
version    : 1.6.2
release    : 17
source     :
    - https://download.gnome.org/sources/gssdp/1.6/gssdp-1.6.2.tar.xz : 410b376deeced9836b57f488f80052fe4a14f89e075b1ceccf28e51f490f9fb9
license    : LGPL-2.0-only
component  : network.util
summary    : A GObject-based API for handling resource discovery and announcement over SSDP.
description: |
    A GObject-based API for handling resource discovery and announcement over SSDP.
builddeps  :
    - pkgconfig(gi-docgen)
    - pkgconfig(gtk4)
    - pkgconfig(libsoup-3.0)
    - pandoc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
