name       : gssdp
version    : 0.14.11
release    : 1
source     :
    - https://download.gnome.org/sources/gssdp/0.14/gssdp-0.14.11.tar.xz : 7bf5aeaf2119fe0bec5f3632ecf39dae15bc85276c72c2ad8dd4b0e345c6535a
license    : LGPL-2.0
summary    : A GObject-based API for handling resource discovery and announcement over SSDP.
description: |
    A GObject-based API for handling resource discovery and announcement over SSDP.
builddeps  :
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
