name       : gssdp
version    : 1.2.2
release    : 9
source     :
    - https://download.gnome.org/sources/gssdp/1.2/gssdp-1.2.2.tar.xz : cabb9e3b456b8354a55e23eb0207545d974643cda6d623523470ebbc4188b0a4
license    : LGPL-2.0-only
component  : network.util
summary    : A GObject-based API for handling resource discovery and announcement over SSDP.
description: |
    A GObject-based API for handling resource discovery and announcement over SSDP.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
