name       : gssdp
version    : 1.2.0
release    : 6
source     :
    - https://download.gnome.org/sources/gssdp/1.2/gssdp-1.2.0.tar.xz : 22cbef547f522f0b062933e302482ebdb397e2f3703899757562ddffbbfd00d1
license    : LGPL-2.0-only
component  : network.util
summary    : A GObject-based API for handling resource discovery and announcement over SSDP.
description: |
    A GObject-based API for handling resource discovery and announcement over SSDP.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
