name       : gssdp
version    : 1.0.2
release    : 3
source     :
    - https://download.gnome.org/sources/gssdp/1.0/gssdp-1.0.2.tar.xz : a1e17c09c7e1a185b0bd84fd6ff3794045a3cd729b707c23e422ff66471535dc
license    : LGPL-2.0
component  : network.util
summary    : A GObject-based API for handling resource discovery and announcement over SSDP.
description: |
    A GObject-based API for handling resource discovery and announcement over SSDP.
builddeps  :
    - pkgconfig(libsoup-2.4)
    - gtk-doc
setup      : |
    %configure --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
