name       : gssdp
version    : 1.2.1
release    : 7
source     :
    - https://download.gnome.org/sources/gssdp/1.2/gssdp-1.2.1.tar.xz : 6b57b79a96e229367981b6f00474e4bbc795909a2d3160c748cba3395b3556d3
license    : LGPL-2.0-only
component  : network.util
summary    : A GObject-based API for handling resource discovery and announcement over SSDP.
description: |
    A GObject-based API for handling resource discovery and announcement over SSDP.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
