name       : gssdp
version    : 0.14.16
release    : 2
source     :
    - https://download.gnome.org/sources/gssdp/0.14/gssdp-0.14.16.tar.xz : 54520bfb230b9c8c938eba88d87df44e04749682c95fb8aa381d13441345c5b2
license    : LGPL-2.0
summary    : A GObject-based API for handling resource discovery and announcement over SSDP.
description: |
    A GObject-based API for handling resource discovery and announcement over SSDP.
builddeps  :
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
